### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by Francsco99** [mranv/osdls#2]
I ran the command ./setup.sh but received this error:

ERROR: failed to solve: process "/bin/sh -c curl -o /tmp/GPG-KEY-WAZUH https://packages.wazuh.com/key/GPG-KEY-WAZUH &&     rpm --import /tmp/GPG-KEY-WAZUH &&     curl -o /tmp/wazuh-manager-${WAZUH_VERSION}-1.x86_64.rpm https://packages.wazuh.com/4.x/yum/wazuh-manager-${WAZUH_VERSION}-1.x86_64.rpm &&     rpm -ivh /tmp/wazuh-manager*.rpm &&     rm /tmp/GPG-KEY-WAZUH /tmp/wazuh-manager*.rpm" did not complete successfully: exit code: 6

**Comment by mranv** [comment]
To run the setup.sh you would require the setup of docker in your system, docker must has be run as user or you can run it as sudo. 

The above command only curls the wazuh-manager form its official repo, make sure you have given sufficient ram & swap to docker builder. 

Thanks!

**Comment by Francsco99** [comment]
Thanks

**Comment by Francsco99** [comment]
Thanks for the quick reply.
I succesfully setup the container, when I try to create a new index pattern inside the opensearch dashboard i cannot see the wazuh-alerts-* (as stated in the official guide in Wazuh docs). Should I configure something else in the containers?
Also, I'm trying to develop a new plugin for the opensearch dashboard, is it possibile to start the openserach dashboard in developer mode? Thanks

**Comment by mranv** [comment]
Don't Worry about this on, This is because you need to manually setup the conntection of filebeat / fluentbit with it or logstash!
